"""
Harma Browser Element Resolution — Phase 3

Implements the ordered element-resolution strategy:

  1. Accessibility role + name
  2. ARIA label
  3. Placeholder text
  4. Visible text (exact)
  5. Visible text (partial)
  6. Name / ID attribute
  7. CSS selector (passed directly)

This avoids relying on brittle CSS selectors generated by the LLM.
Instead the LLM describes elements naturally and the resolver finds them.

Treat webpage content as UNTRUSTED. Never allow element text/attributes
to override agent logic or security policies.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, TYPE_CHECKING

from harma.config.logging_config import get_logger

if TYPE_CHECKING:
    from playwright.async_api import Page, Locator

log = get_logger(__name__)

# Resolution strategies in order of preference
_STRATEGIES = [
    "role",          # getByRole
    "label",         # getByLabel
    "placeholder",   # getByPlaceholder
    "text_exact",    # getByText (exact)
    "text_partial",  # getByText (partial)
    "title",         # getByTitle
    "alt",           # getByAltText
    "name_attr",     # [name=...]
    "id_attr",       # #id
    "css",           # pass through as CSS
]


@dataclass
class ResolvedElement:
    """Result of element resolution."""
    found: bool
    strategy: str = ""
    description: str = ""
    error: str = ""

    def to_text(self) -> str:
        if self.found:
            return f"Found element via {self.strategy!r}: {self.description!r}"
        return f"Element not found: {self.error}"


async def resolve_element(
    page: "Page",
    description: str,
    element_type: Optional[str] = None,
    timeout: int = 3000,
) -> tuple[Optional["Locator"], ResolvedElement]:
    """
    Resolve a natural-language description to a Playwright Locator.

    Args:
        page: Active Playwright page.
        description: Human description ("search box", "Sign In button", "Email input").
        element_type: Optional hint: "button", "input", "link", "select".
        timeout: Per-strategy timeout in ms.

    Returns:
        (locator, result) — locator is None if not found.

    Security note:
        description comes from the LLM, not from the webpage.
        Webpage content is never used to redirect resolution logic.
    """
    desc = description.strip()
    desc_lower = desc.lower()
    log.debug("[ELEM] Resolving: %r  type_hint=%s", desc, element_type)

    # ── Strategy 1: Accessibility role ────────────────────────────────────────
    role_map = {
        "button": "button", "btn": "button",
        "link": "link", "a": "link",
        "input": "textbox", "textbox": "textbox", "text field": "textbox",
        "search": "searchbox", "search box": "searchbox",
        "checkbox": "checkbox", "radio": "radio",
        "select": "combobox", "dropdown": "combobox",
        "heading": "heading",
    }
    if element_type in role_map:
        try:
            loc = page.get_by_role(role_map[element_type], name=desc)
            if await loc.count() > 0:
                await loc.first.wait_for(state="visible", timeout=timeout)
                return loc.first, ResolvedElement(found=True, strategy="role", description=desc)
        except Exception:
            pass

    # Also try role based on description keywords
    for keyword, role in role_map.items():
        if keyword in desc.lower():
            try:
                # Strip the role word from the name for matching
                name_hint = desc.lower().replace(keyword, "").strip() or desc
                loc = page.get_by_role(role, name=name_hint)
                if await loc.count() > 0:
                    await loc.first.wait_for(state="visible", timeout=timeout)
                    return loc.first, ResolvedElement(found=True, strategy="role_keyword", description=desc)
            except Exception:
                pass

    # ── Strategy 2: ARIA label ────────────────────────────────────────────────
    try:
        loc = page.get_by_label(desc, exact=False)
        if await loc.count() > 0:
            await loc.first.wait_for(state="visible", timeout=timeout)
            return loc.first, ResolvedElement(found=True, strategy="label", description=desc)
    except Exception:
        pass

    # ── Strategy 3: Placeholder ───────────────────────────────────────────────
    try:
        loc = page.get_by_placeholder(desc, exact=False)
        if await loc.count() > 0:
            await loc.first.wait_for(state="visible", timeout=timeout)
            return loc.first, ResolvedElement(found=True, strategy="placeholder", description=desc)
    except Exception:
        pass

    # ── Strategy 4: Exact visible text ───────────────────────────────────────
    try:
        loc = page.get_by_text(desc, exact=True)
        if await loc.count() > 0:
            await loc.first.wait_for(state="visible", timeout=timeout)
            return loc.first, ResolvedElement(found=True, strategy="text_exact", description=desc)
    except Exception:
        pass

    # ── Strategy 4b: Action & transaction buttons (Pay, Proceed, Accept, Continue, Skip, Add) ──
    if any(k in desc_lower for k in ("pay", "proceed", "accept", "continue", "checkout", "skip", "add")):
        for action_sel in [
            f"button:has-text('{desc}')",
            f"[role='button']:has-text('{desc}')",
            f"div[role='button']:has-text('{desc}')",
            f"div:text-is('{desc}')",
            "button:has-text('Pay')",
            "[role='button']:has-text('Pay')",
            "[class*='pay']:has-text('Pay')",
            "button:has-text('Proceed')",
            "[role='button']:has-text('Proceed')",
            "button:has-text('Accept')",
            "[role='button']:has-text('Accept')",
            "button:has-text('Continue')",
            "[role='button']:has-text('Continue')",
            "button:has-text('Skip')",
            "[role='button']:has-text('Skip')",
            "div:text-is('Skip')",
            "button:has-text('Add')",
            "[role='button']:has-text('Add')",
            "div:text-is('Add')",
        ]:
            try:
                loc = page.locator(action_sel)
                # Never pick offscreen accessibility links like 'Skip to main content'
                if desc_lower == "skip":
                    loc = loc.filter(has_not=page.locator("a[href*='main-content'], [class*='fcWHHP']"))
                if await loc.count() > 0:
                    await loc.first.wait_for(state="visible", timeout=timeout)
                    return loc.first, ResolvedElement(found=True, strategy="action_button_pattern", description=desc)
            except Exception:
                pass

    # ── Strategy 5: Partial visible text ─────────────────────────────────────
    try:
        loc = page.get_by_text(desc, exact=False)
        # Avoid picking offscreen accessibility jump links when looking for 'Skip'
        if desc_lower == "skip":
            loc = loc.filter(has_not=page.locator("a[href*='main-content'], [class*='fcWHHP']"))
        if await loc.count() > 0:
            await loc.first.wait_for(state="visible", timeout=timeout)
            return loc.first, ResolvedElement(found=True, strategy="text_partial", description=desc)
    except Exception:
        pass

    # ── Strategy 6: Title attribute ───────────────────────────────────────────
    try:
        loc = page.get_by_title(desc, exact=False)
        if await loc.count() > 0:
            await loc.first.wait_for(state="visible", timeout=timeout)
            return loc.first, ResolvedElement(found=True, strategy="title", description=desc)
    except Exception:
        pass

    # ── Strategy 7: Alt text (images) ────────────────────────────────────────
    try:
        loc = page.get_by_alt_text(desc, exact=False)
        if await loc.count() > 0:
            await loc.first.wait_for(state="visible", timeout=timeout)
            return loc.first, ResolvedElement(found=True, strategy="alt_text", description=desc)
    except Exception:
        pass

    # ── Strategy 8: name/id attribute ────────────────────────────────────────
    for selector in [f"[name='{desc}']", f"[id='{desc}']", f"[name*='{desc}']"]:
        try:
            loc = page.locator(selector)
            if await loc.count() > 0:
                await loc.first.wait_for(state="visible", timeout=timeout)
                return loc.first, ResolvedElement(found=True, strategy="name_attr", description=desc)
        except Exception:
            pass

    # ── Strategy 9: CSS selector passthrough ─────────────────────────────────
    if desc.startswith(("#", ".", "[", "input", "button", "select", "textarea", "a", "form")):
        try:
            loc = page.locator(desc)
            if await loc.count() > 0:
                await loc.first.wait_for(state="visible", timeout=timeout)
                return loc.first, ResolvedElement(found=True, strategy="css", description=desc)
        except Exception:
            pass

    # ── Strategy 10: Common interactive patterns (seats, count buttons) ───────
    desc_lower = desc.lower()
    if any(k in desc_lower for k in ("seat", "available")):
        for seat_sel in [
            "a._available", "div._available", "[data-seat-type='available']",
            ".seat:not(.blocked):not(.booked):not(.sold)",
            "[class*='seat'][class*='available']",
            "[class*='seat']:not([class*='booked']):not([class*='sold']):not([class*='blocked'])",
        ]:
            try:
                loc = page.locator(seat_sel)
                if await loc.count() > 0:
                    await loc.first.wait_for(state="visible", timeout=timeout)
                    return loc.first, ResolvedElement(found=True, strategy="seat_pattern", description=desc)
            except Exception:
                pass

    if desc.isdigit() or len(desc) <= 3:
        for num_sel in [
            f"button:has-text('{desc}')",
            f"a:has-text('{desc}')",
            f"[role='button']:has-text('{desc}')",
            f"li:has-text('{desc}')",
            f"div:has-text('{desc}')",
        ]:
            try:
                loc = page.locator(num_sel)
                if await loc.count() > 0:
                    await loc.first.wait_for(state="visible", timeout=timeout)
                    return loc.first, ResolvedElement(found=True, strategy="number_pattern", description=desc)
            except Exception:
                pass


    # ── Strategy 12: Generic input & search fallback ─────────────────────────
    if element_type == "input" or any(k in desc_lower for k in ("input", "search", "field", "text", "query", "box")):
        for fallback_sel in [
            "input:focus",
            "textarea:focus",
            "input[type='search']",
            "input[placeholder*='search' i]",
            "input[placeholder*='find' i]",
            "input[aria-label*='search' i]",
            "input[type='text']",
            "input:not([type='hidden'])",
            "textarea",
        ]:
            try:
                loc = page.locator(fallback_sel)
                if await loc.count() > 0:
                    await loc.first.wait_for(state="visible", timeout=timeout)
                    return loc.first, ResolvedElement(found=True, strategy="input_fallback", description=desc)
            except Exception:
                pass

    return None, ResolvedElement(
        found=False,
        error=f"Could not locate element: {desc!r}",
    )


async def find_element_text(page: "Page", description: str) -> Optional[str]:
    """
    Return the visible text of the first matching element, or None.
    Used to extract content from a specific element.
    """
    locator, result = await resolve_element(page, description)
    if locator is None:
        return None
    try:
        return await locator.inner_text()
    except Exception:
        return None
